user=input()
lastname=input()
address=input()
gender=input()
tel=input()
print("---Customer Detail---")
print("Name:", user, lastname)
print("Address:",address)
print("Gender:",gender)
print("Tel", tel)